[package]
name = "aoc-2022"
version = "0.1.0"
edition = "2021"

[dependencies]

[lib]
name = "aoc"
path = "src/lib.rs"

[[bin]]
name= "template"
path = "src/bin/template.rs"

[[bin]]
name= "day1"
path = "src/bin/day1.rs"
