name: ci

on:
  push:
    branches: [main]
    tags:
  pull_request:
  workflow_dispatch:


jobs:
  fmt_and_test:
    name: Rust CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rustfmt
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --check
      - uses: actions-rs/cargo@v1
        with:
          command: test
